export const drafts = [
  {
    id: 'teach-to-the-tests',
    title: 'Teach To The Tests',
    author: 'Mark Stewart Greenstein',
    date: 'October 1, 2026',
    category: 'Education',
    excerpt: 'Four words that should not be radical, and the reason an average Maryland student gets a better hearing from elite colleges than a Mississippi valedictorian.',
    contentFull: [
      'How do we improve education? At least in the secondary schools, where I do have expertise, I have four words. This should not be radical. I have a video elsewhere about some semi-radical things worth considering; this is not one of them. But to some teachers, it is unspeakable.',
      'Four words for secondary school: teach to the test.',
      'You know who does like it? Parents do. College admission committees do. And most mature students do — at least compared with the material they consider out there and impractical for them. They pay attention. Those with practical ambitions, and that includes seventh and eighth graders who want to go on and do something professional but don\'t yet know what, already know that learning at the standardized level and mastering it pays dividends. Most of their parents would like teachers to be instilling that.',
      'We can do it as a curriculum without cheapening the curriculum, because standardized tests — with one big exception — generally test good stuff. Teaching to them is not a bad detour. It is straight on. And let teachers who would like to detour beyond that do so. Enthrall your kids with what you are also passionate about. But be passionate about their successes.',
      'You know who does this? Maryland. Maryland has the highest standardized test scores in most years across the fifty states. Maryland has a high percentage of elite college professors as constituents. It has a lot of highly paid Washington-area government officials. It has defense contractors. They demand success, and the college admissions committees see that, and it applies to all of Maryland\'s students to some extent. By contrast, in Mississippi you can be the valedictorian and still not get into an elite college, because they don\'t trust a Mississippi education against the standards. In Maryland you can be average and still have a leg up — a good leg up — for elite college admission and for scholarships to those colleges, because they perceive that the average is quite high.',
      'In every practical science there might be only one or two teachers for it. But with the schools wired up, every student would be able to access it.',
      'Look, our time with the kids is really limited. In an average school month you have at most a hundred hours to teach. So what am I not that interested in? Dickens. Edith Wharton. That is for a little bit of summer reading, and if a kid is enthused in the first few chapters, keep on going. Pile on more Edith Wharton, or similar English literature. Pile on Harry Potter, though, if that is what a kid is learning better vocabulary from while being entertained, and learning about the world — not as good as old England, but it is still old England. And please supplement modernity with short, practical articles in our summer reading.',
      'Here is the absolute opposite: Shakespeare, which I love now. I did not as a twelfth grader, because it was taught so badly. We had to plod through line after line, word after word, of four-hundred-year-old words. It couldn\'t be enjoyable. It was a chore, until I saw a play, which is funny. Just having a video in school for act one will get so many more students engaged and wanting to read more. What are the words behind this? Shakespeare is humorous. It is hard to be humorous even in our own time, and this guy is funny, and it has lasted 425 years. Absolutely amazing. That would give great appreciation.',
      'But it is off standard. Don\'t make it a requirement. Make it optional. Kids can become Shakespearean scholars in college, maybe even near the end of high school if they have really latched on to it. Until then: be practical, be enjoyable, and teach to the tests, so that the practicing — and the enjoyability that kids gain from school — gives them long-term success.',
    ].join('\n\n'),
    sourceVideo: 'https://youtu.be/YmGiCZzeGHE',
    sourceWords: 682,
  },
  {
    id: 'homelessness-in-connecticut',
    title: 'Homelessness Begins In The Mindset',
    author: 'Mark Stewart Greenstein',
    date: 'October 1, 2026',
    category: 'Civics',
    excerpt: 'Two very different prescriptions for two very different kinds of homelessness: bridge loans for those who want to work, and psychiatric treatment for those who do not.',
    contentFull: [
      'Two issues have received some attention lately, one national and one local. They are related in spelling only, and they should not be confused with one another. The legislators who have to grapple with this have the brain power to do so. But I have worry, and there is cause for it.',
      'Number one, legislation gets separated, and legislation gets amalgamated beyond the control of any one leader. That is often the case, and then you end up with bad legislation. Number two, legislation often comes with compromise when clear, strident solutions are better. Number three, good legislation often succumbs to feelings, and that is especially true when Democrats control our chamber. Number four, good legislation often comes with outside businesses or outside donors greatly influencing it.',
      'Let\'s be smart about it. Here are two areas where outside groups, I think, deserve to make the first recommendations before the legislature. Allow either the governor or the legislature to empower groups of citizens. Wise citizens. They don\'t have to hold PhDs. Wise often means just plain experienced in life. PhD holders often contravene common sense. So when a group can get good recommendations, the legislature hopefully can do an up-or-down vote and not make it convoluted.',
      'Here are the principles behind this. Homelessness among adults almost always stems from an individual\'s mindset, and homelessness has at least two prescriptions, very different from one another.',
      'For those with a short-term deficit — they are in bankruptcy, they have suffered an injury, a loss of work — bridge loans, to keep them in their homes, whether renting or owning and paying a mortgage. These I do think are worthy state functions, if private lenders are unavailable. These people want to work, and they will repay their debt almost certainly. Let\'s not disrupt their lives any more than they already have been. If they still don\'t repay, then all right, that rare time it might be on the state. But the state can nimbly assess who wants to work and repay a debt and who doesn\'t.',
      'Now, to those who don\'t and are homeless: they are almost certainly mentally ill. Those who don\'t want to work, I believe by definition have a mental illness. They don\'t belong in a capitalist country. So with a long-standing mindset — four months or more of a person not wanting to work — they have to be treated differently, and treated not in a home that we are going to pay for, but in a psychiatric place that yes, we do have to pay for, for a while. It should come with healing, getting them over this. The psychiatric facility is probably not going to be a pleasant place, but it is better than vagrancy on the street. That is the condition.',
      'Once treated well enough for release, those mentally ill could have halfway houses. Sole ownership might take a while. But until then, occupancy in a group home has the benefit of helping the newly released person socialize better, and maybe help them with jobs, or at least job skills, to continue on a path toward independence.',
      'There is enough housing in this state for all 3,600,000 residents. There are empty houses, both single-family and multi-family. There are buildings that can be reconverted — my business partner is doing one of them in Hartford now. They can be profitable if some regulations are reduced so you move faster, and thank the city of Hartford for now doing this with some developers. It is a good thing. And the owners of this kind of housing, be they these individuals themselves or their landlords, can earn stock market rates of return.',
      'Any well-balanced adult can get decent work. This is not 1931 and a deep recession. Any adult who wants to work can find employment in this state somewhere, including remunerative online work from where they are. Even at minimum wage, you work 50 to 55 hours a week and it yields at least $3,000. So spending $1,000 of that on your housing still leaves you $2,000 a month. And one of those two jobs — because 50 hours a week probably takes two jobs to do — is likely to pay well above minimum wage when you do well for them. Six months later you are into a raise, maybe a 40-hours-plus-benefits type of work situation.',
      'That is your on-ramp, for those who are homeless but not permanently mentally ill.',
    ].join('\n\n'),
    sourceVideo: 'https://youtu.be/5rBt4XIou_Q',
    sourceWords: 776,
  },
  {
    id: 'welfare-for-whom',
    title: 'Aid The Individual, Not The Group',
    author: 'Mark Stewart Greenstein',
    date: 'October 1, 2026',
    category: 'Liberty & Politics',
    excerpt: 'Advocates want Connecticut to feed 36,000 people in three groups after SNAP ends, but charity that judges groups instead of individuals fails both the giver and the needy.',
    contentFull: [
      'As reported in the Connecticut Mirror, the ending of the SNAP benefit has advocates for 36,000 people in Connecticut asking us to spend money to feed them. They come in three groups: young adults, veterans, and immigrants. Three groups, and a big difference among them. Let me parse them.',
      'Which one is not worthy? As a group, not as individuals, I think you have to say immigrants, who are supposed to be working if they are here, and thus not starving. If they are here on a green card, they are working. If they are here with a sponsor, the sponsor is pledging to take care of them in case bad things befall their economics. So an immigrant who is not taking care of himself should not be calling on government welfare.',
      'Now, there is a place for private welfare, because a lot of them are nice people. A lot of them, after they get over a hump, will be very productive people, good Americans in the making. But look to private. That might be their own employer. If an employer knows a man is on the verge of starving, almost any employer is going to find some bonus turkey each week, some extra to get this guy fed and to work. If not, there is family, there are neighbors, there are churches, there are other charities that are not government — which means it is not forced from our pocketbooks.',
      'The other groups, veterans and young people, often have disasters befall them, so that they are less capable of helping themselves. Our immigration system, as we know, is totally screwed up. But at the core, people who come here are not here to take, at the outset or even long term. They are here because they are productive. They can take care of themselves.',
      'Now, as I think you know, I am not a big fan of giving welfare dollars, private or government, on a group-by-group basis. We should be more discerning, down to individuals. This is Trump\'s big failing in my mind on the immigration front: that it is a whole country he is going to say no to, everyone from there, including very good people. The parsing of good from not-so-good is something that even government can do.',
      'Again, I think private should have the first crack. They do it very well. I am part of a Jewish charitable group where they know the people who have been applying for aid, or maybe not even applying — they are really down and out, and somebody else is applying for them. They scrutinize the situation. Is this a good person to be aiding? Or is this a person we give money, clothes and food to who is just going to buy booze? Discernment is right. It is the right thing to do for them, and for us, to feel good about where our private and, yes, our public welfare dollars are going.',
      'Even government can do this. Make individualized decisions with it. You uplift almost everyone who is needy, because they need to step up as individuals. Yes, I am down right now, but I am not out. I want to rebound, and I have gratitude for the agency or the individuals who are helping me.',
      'When somebody is classified as just part of a group, they are suddenly entitled. They don\'t have to justify. They are not even likely to try. Oh, I am part of a designated group: veteran, young, immigrant. And because they are not escaping the group to a higher status, they stay as a group in what I think is a lower status.',
      'Individualism uplifts, even when it comes to charity.',
    ].join('\n\n'),
    sourceVideo: 'https://youtu.be/N6_aTedMrZY',
    sourceWords: 603,
  },
];
export default drafts;
