export const drafts = [
  {
    id: 'come-on-up',
    title: 'New Yorkers, Come On Up to Connecticut',
    author: 'Mark Stewart Greenstein',
    date: 'October 1, 2026',
    category: 'Economy',
    excerpt: 'Sell what you own in the city, pocket the difference, and get three times the house — an invitation to the New Yorkers already thinking about leaving.',
    contentFull: [
      'This is for families in southern New York, and especially in New York City. I am in Connecticut, where I help people get into nice Connecticut homes.',
      'To those of you who have been thinking about heading here — maybe just for a vacation home, maybe for a permanent one — I would like to introduce you to great properties you can have for about a third of the price. Sell what you own now. Pocket the difference. You will have more acreage, more room inside, probably a pool if you want one. And if you are mostly paid in New York, you can still pocket six or maybe seven figures.',
      'A lot of you have been thinking about moving, even before the last mayoral election. Well, come on up. At least see what we have to offer, and how it will almost certainly suit your kids\' schooling, your recreation, your better quality of life. Ask the New Yorkers who have already left and who you still keep in touch with. Are they all ready to come back? Probably not, because they like it here.',
      'Allow me to show you homes that still have an element of the urban life you have come to enjoy.',
      'If you are in the Bronx now, Stamford has a lot of what you already have, and it is only 20 miles away. Just come on up and take a visit. You can easily get back to the old stomping grounds — you can get to Stamford in less time than you can get to Brooklyn.',
      'If you are in Brooklyn now, how about New Haven? It has always been a hip place. It has two neat universities, a lot of good nightlife, and tremendous pizza.',
      'If you are in Queens, consider Waterbury. It is on the train line, so it is an easy trip back if you still cannot rip yourself away. It is a burgeoning city with very many cultures, just like Queens, but without the compactness of Queens, and without the crap that comes from New York\'s government and New York State.',
      'And finally, those of you in Manhattan: look at Hartford. Not as much as Manhattan, but Hartford has its restaurants. Hartford has its nightlife, its museums, its culture. And it has some things that New York can never have. Recreation here is wonderful and easily had. So are sports. Not eight professional teams, but a couple of really good college teams and some very good minor league teams. You can have the recreation, and your kids can have the sports you look for, without all of the closeness and the hassle.',
      'I would love to show you more. Come on up.',
    ].join('\n\n'),
    sourceVideo: 'https://youtu.be/FdM7ic_3Ztg',
    sourceWords: 454,
  },
  {
    id: 'other-half-of-affordability',
    title: 'The Other Half of Housing Affordability',
    author: 'Mark Stewart Greenstein',
    date: 'October 1, 2026',
    category: 'Economy',
    excerpt: 'Legislators and the media argue only about pushing prices down; the faster route to an affordable home is letting Connecticut families keep the money the federal government takes.',
    contentFull: [
      'Home affordability has two components, and it is unfortunate that legislators and the media tend to focus on only one of them: making the price of home rentals or home mortgages lower. I do not want to focus on that. I want the other half: making the ability to pay much higher. Increasing people\'s earnings. Increasing people\'s wealth.',
      'A legislature can do a lot here. I am in Connecticut, and I have put forward what I hope this legislature will do: allow a federal tax opt-out.',
      'The opt-out means anyone in Connecticut who does not want to pay the unconstitutional portion of their taxes, and will not use those services, does not have to. Take highways, which are of dubious constitutionality. We have built them, and I am not saying to turn them down — but if you will never use them, you can opt out. If you would use them, a pay-as-you-go system for construction and maintenance would be good. To some extent we have that with the gas tax, though electric vehicles are not taxed on their usage, and in fact cause more wear than the average gas-powered car because of those big heavy batteries. It is an imperfect system. Even so, pay-as-you-go beats what the government extracts from us now. Extracts. Confiscates. We have no choice.',
      'But a state can say its citizens who opt out are protected. We are not going to let federal extraction happen. If we can block federal takings from banks, we will do so. If federal teams send a SWAT force against one person in a neighborhood who has been withholding — conscientiously withholding — we will protect against that too.',
      'The great news is that in Trump and Vance we have the best pair maybe ever — since Lincoln, anyway — the best presidential and vice-presidential mindset for not extracting money from people to benefit the feds. In a way, an opt-out benefits the federal treasury: they will not have to spend on the people who opt out. If that is half of Connecticut, that is half of one percent of the budget they save. And they save more than what we withhold, because deficit spending runs about 20 percent more than the federal government actually takes in. We are doing Trump and Vance, and anyone in a federal bureaucratic position, a favor.',
      'So let the opt-out start immediately. A 50 percent withholding from a $10,000 federal income tax releases $5,000 to that family. The Social Security tax could be a 100 percent opt-out. I do not want any part of it. I probably deserve some money back, but take it, and do not tax me any damn more. That drops your liability to zero.',
      'All told, say it is an earner on an $80,000 a year salary. That gets this earner $14,000 more annually — and applied to housing, at least 30 percent more house, whether renting or making mortgage payments. You are not sacrificing any other pleasures. You are not scrimping on your kids\' educations. And we are not taking down any state coffers, because this is from the feds.',
      'What are you giving up? Your Social Security and Medicare benefits — which you are probably not going to see unless you are destitute at 80 years old. You know this. So give it up. It is too imbalanced. The bankruptcy is there right now, and the government does not want to admit it. At some point they will have to scrimp on payments to people who are not destitute. It will be means-tested, in their terms.',
      'That is opt-out, number one. Here is number two: the slow and steady way to improve your earning power. Take that next job opportunity, or bargain for more responsibilities and higher pay at the job you currently have. Build your education — most employers, frankly, reward holders of science degrees. State programs might help here too. But notice that the essence comes from the individual.',
      'Slow and steady rising income makes housing much more affordable. And fast, thanks to a good legislature if it will follow this proposition, dramatically raises buying power, because you have more of your own wealth to keep.',
    ].join('\n\n'),
    sourceVideo: 'https://youtu.be/SrySqmuGTn4',
    sourceWords: 773,
  },
];
export default drafts;
